### ISSUE TITLE
Parameter field is not case sensitive for github command

### ISSUE THREAD

**Issue by SwaminathanViswa** [AY2425S1-CS2103T-T11-2/tp#150]
![image](https://github.com/user-attachments/assets/010ddb5c-bc26-433d-bbd0-42e3b0f68ce6)
When the command is executed, it brings me to the github under point 4 and not 3. Maybe making it all case sensitive will make it easier for the user.

**Comment by Incogdino** [comment]
Hmm would it be better if we do not allow inputs for the same name regardless of the case? If they do not have the same name, there would be less confusion for the user.

**Comment by DesSnowy** [comment]
This the same for some other commands such as `view`. I think its best if we standarise throughout the code if NAME should be case sensitive or not.

**Comment by SwaminathanViswa** [comment]
Yeah, I agree with @DesSnowy. It would be easier if we solve the root cause so that everything else is standardised

**Comment by Incogdino** [comment]
I believe having name field to be case insensitive would be a good idea since it is better to remember two different person with the same name by some other means like adding the surname rather than by the case.

**Comment by Incogdino** [comment]
Hmm why wasn't this closed
