### ISSUE TITLE
Import requires no blank line in the csv file

### ISSUE THREAD

**Issue by SwaminathanViswa** [AY2425S1-CS2103T-T11-2/tp#151]
![image](https://github.com/user-attachments/assets/07273cdf-3b98-4396-85d9-5e8091cf2b04)

When my csv file is as such, it returns me this error. 

![image](https://github.com/user-attachments/assets/011c8481-c966-49c7-ab09-38268308159a)

Since the error message mentions `names `but there is no `name` field in the parameter, users might get confused. 

A simple fix could be to include the constraint in the user guide and could also change the error message to `There should be no preceding blank lines in the .csv file.` (along those lines)

**Comment by Incogdino** [comment]
To add on, I think we can also specify a format required for the import csv file in the user guide?

**Comment by tohjh** [comment]
Will make it such that empty rows are skipped over as i realised that if you use excel to edit the data, clearing the last row will result in an empty data row separated by comas which causes issues when reading anyways
