### ISSUE TITLE
Unable to manually add telegram field to csv file

### ISSUE THREAD

**Issue by SwaminathanViswa** [AY2425S1-CS2103T-T11-2/tp#186]
![image](https://github.com/user-attachments/assets/ad635b4b-0189-4081-87bc-6de5cb7743ed)

When I export it to a csv file and I manually add a new user, I am unable to add in '@telegram' since excel does not support it. And when I don't put in the '@', it throws me the error as shown below.

![image](https://github.com/user-attachments/assets/b123bccf-51aa-469d-9092-c90e07fa14bb)

**Comment by Incogdino** [comment]
As discussed I think this is just an excel issue which triggers the command when using @. 

A similar thread online suggested a solution to add an apostrophe at the start to escape that behavior. I tried it and it imports without any issues.
https://superuser.com/questions/867072/how-to-prevent-excel-from-inserting-formulas-when-typing-or-at-the-beginning

I believe this an excel thing? Perhaps it will be a good idea to add this into our user guide (under known issues) that advices users that opens the csv file with excel to take note of this.

**Comment by DesSnowy** [comment]
Yup its an excel thing since @ is used for its formulas/functions. Other way of opening CSV files should not have such an issue.
