### ISSUE TITLE
[PE-D][Tester C] Ui flaw: Not easy to see the assignments

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-2/tp#286]
When inputting `ag` to view assignments, it is not easy to see what assignments I can allocate the students' grades to due to the small text size. It is fine for 3 assignments, but if there are more, it could be an issue.

![image.png](https://raw.githubusercontent.com/lrongyi/ped/main/files/9b348971-d1e8-4a47-9772-47a07ca04bae.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lrongyi/ped#1

**Comment by Incogdino** [comment]
Don't think we can change this anymore since it is considered a UI change?

**Comment by DesSnowy** [comment]
If we have space in future Enhancements we can consider adding it there. Else its just minor UI issues since they still can scroll.
