### ISSUE TITLE
[PE-D][Tester C] Functionality Bug: Adding Grade with more than 2 d.p.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-2/tp#295]
Unable to add a grade of more than 2 decimal places. Input and display is as shown:

![image.png](https://raw.githubusercontent.com/lrongyi/ped/main/files/b8bcb881-c38a-4d4f-976d-49a1e1c3f21e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: lrongyi/ped#5

**Comment by tohjh** [comment]
Assignments are seldom graded to more than 2dp. Doing so in the app will truncate the score

**Comment by DesSnowy** [comment]
Closed by #346
