### ISSUE TITLE
[PE-D][Tester E] User Guide pg 11: misleading example for email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#301]
The box is highlighting email restrictions but you have put examples for tags. Perhaps you are intending the examples for emails?

![image.png](https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/4f2e109c-1df7-4dda-9a17-e07c7b79fa0f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: somethingfishyfishy/ped#2

**Comment by Incogdino** [comment]
This needs updating

**Comment by DesSnowy** [comment]
Duplicate of #293
