### ISSUE TITLE
[PE-D][Tester D] Keying in delete command word together with the user fields from the add command results in unexpected behaviour

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#303]
![Screenshot 2024-11-08 at 5.52.38 PM.png](https://raw.githubusercontent.com/naythee169/ped/main/files/22bf7b02-4817-4cf6-8bd4-a2771102982b.png)

![Screenshot 2024-11-08 at 4.56.07 PM.png](https://raw.githubusercontent.com/naythee169/ped/main/files/7e69946c-29c3-4022-ad36-95127c561a30.png)

When typing in the delete command with the add command parameters as show above, I would expect an error message saying invalid command format as seen in the first screenshot but instead I receive an incorrect error message about the "name" field formatting, which shows that the incorrect command is not being parsed correctly.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: naythee169/ped#4

**Comment by DesSnowy** [comment]
I think this is the intended output. Maybe we should put somewhere in the ug: any prefixses not specified in the command format will be treated as text for the previous prefix
