### ISSUE TITLE
[PE-D][Tester B] The app allows too short Telegram usernames.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#308]
The application doesn't handle error when I try to add new student with too short telegram (e.g. @a). https://core.telegram.org/method/account.checkUsername.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: kienvumrpm/ped#5

**Comment by Incogdino** [comment]
This fix can be implemented. Would solve some of the telegram name too long issues as well

**Comment by DesSnowy** [comment]
Cannot be fixed in the code, maybe can add in the UG or something
