### ISSUE TITLE
[PE-D][Tester C] Feature Flaw: Unable to add more weeks to track attendance

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#312]
Unable to add more weeks to track attendance if need be, or edit the numberings for the week (i.e if I want to track from Week 5 - Week 18, rather than Week 0 - Week 13). This could be problematic if the semester does not only have 13 weeks. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: lrongyi/ped#10

**Comment by Incogdino** [comment]
Since the application is meant for c2030s TAs and cs2030s only occur during the semester, it would make sense that it only has 14 weeks.

Perhaps we can add it under future enhancements if need be to allow for adding more weeks

**Comment by DesSnowy** [comment]
Yup I think we should add it to future enhancements
