### ISSUE TITLE
[PE-D][Tester C] Documentation Bug: Target Audience

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#313]
In the user guide, the target audience is not clearly stated, and does not keep track of professors, and other TAs. (I understand that the target audience is CS2030S  TAs from the release notes)
![image.png](https://raw.githubusercontent.com/lrongyi/ped/main/files/c91e75ad-92fb-47eb-9c7b-685d02ee2ae9.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: lrongyi/ped#11

**Comment by Incogdino** [comment]
Agree there is a bit of inconsistency here. We should update it to be more specific.
