### ISSUE TITLE
[PE-D][Tester A] Inconsistency in command format: addGrade and removeGrade

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-2/tp#314]
Description: inconsistency in stating the command formats for addGrade and removeGrade.

**Help Page's addGrade and removeGrade command format:**

![Screenshot 2024-11-08 at 5.16.50 PM.png](https://raw.githubusercontent.com/jessica2828/ped/main/files/6b33e266-a57b-44e5-bf6a-91499e0aad1d.png)

**UG's addGrade and removeGrade command format:** 

![Screenshot 2024-11-08 at 5.18.44 PM.png](https://raw.githubusercontent.com/jessica2828/ped/main/files/c0984297-f309-4f75-b776-63e94d984f49.png)

There is also discrepancy in the UG's format and shortcut, and the example command provided which may confuse readers.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jessica2828/ped#7

**Comment by Incogdino** [comment]
Can perhaps update the user guide to be more descriptive on what the shortcut means. The help command is meant to serve as a quick reference. If the user does not know how the command works, they should clearly read the user guide instead.

**Comment by DesSnowy** [comment]
I think in the format section, n/ should be changed to name/ as well

**Comment by DesSnowy** [comment]
In the examples, asgn should be changed to a/
