### ISSUE TITLE
[PE-D][Tester D] Exit button should not be located under file button

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#323]
![Screenshot 2024-11-08 at 6.12.02 PM.png](https://raw.githubusercontent.com/naythee169/ped/main/files/27b73406-c329-4cf5-8da6-1773eff7ecb2.png)

After clicking on the file button I receive a pop up for only the exit button, which seems to be a case of incorrect naming of the file button.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: naythee169/ped#12

**Comment by currynia** [comment]
![image](https://github.com/user-attachments/assets/b89141ca-d678-4747-ac6c-e0884069201e)

not an issue
