### ISSUE TITLE
[PE-D][Tester E] scroll pane invisible area that is unscrollable

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#326]
`clear`
`add n/name tele/@telegram e/email@email github/github`
`add n/name2 tele/@telegram e/email@email github/github`
`add n/name3 tele/@telegram e/email@email github/github`
`add n/name4 tele/@telegram e/email@email github/github`
`add n/name5 tele/@telegram e/email@email github/github`

You cannot really tell from the video, but the last attempt is not scrollable. Perhaps you may need to resize the window because this was followed by the previous issue

<i><video controls><source src="https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/43f1d1f6-4db2-46f6-a884-8b73d60b45e2.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/43f1d1f6-4db2-46f6-a884-8b73d60b45e2.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: somethingfishyfishy/ped#6

**Comment by DesSnowy** [comment]
We might be able to fix this by wrapping PersonListPanel inside a scrollPane. Do the rest think this is allowed?

**Comment by DesSnowy** [comment]
WontFix since there is a quick workaround
