### ISSUE TITLE
[PE-D][Tester E] shortened keyword for find does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#330]
![image.png](https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/6f17ac01-ccd4-41ab-bd33-cfd8c2aa87da.png)

`clear`
`add n/name e/email@email tele/@telegram g/github`
`f name`

![image.png](https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/b08f5053-4994-47d3-8b5d-506cb30572e3.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: somethingfishyfishy/ped#9

**Comment by SwaminathanViswa** [comment]
We made an error in the UG, it is supposed to be `fd` and not `f` as the short form for find. The command works fine.
