### ISSUE TITLE
[PE-D][Tester E] find allows invalid keywords

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#331]
the find feature says that only the name parameter would be searched, but there was no validation of the input parameter

![image.png](https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/58040ea7-8c9e-4941-ac6c-d43cf12ba3e7.png)

`find !@#$%^&*(`

![image.png](https://raw.githubusercontent.com/somethingfishyfishy/ped/main/files/c0715a84-e3c5-427d-b60f-fff43c534f19.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: somethingfishyfishy/ped#10

**Comment by Incogdino** [comment]
![image](https://github.com/user-attachments/assets/1ccb807e-7d0a-4a70-a463-f64237eef07b)


Not really a feature flaw since it does what it needs to do. Can leave it for now.
