### ISSUE TITLE
[PE-D][Tester A] Quick Start section in UG might be hard to understand for target users

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-2/tp#339]
As per UG,

![Screenshot 2024-11-08 at 8.47.23 PM.png](https://raw.githubusercontent.com/jessica2828/ped/main/files/6d933ed6-88b3-4093-90a0-36617c498412.png)

Considering the target user as TAs in general, the explanations in the Quick Start section might be hard to understand (especially when the users do not have sufficient technical knowledge):

![Screenshot 2024-11-08 at 8.46.33 PM.png](https://raw.githubusercontent.com/jessica2828/ped/main/files/993bc40c-dde6-4a91-bca3-5149ec679501.png)

Instruction such as "cd into home folder you put the jar file in" might not be very straightforward, and "type `view name/Alex Yeoh` " might sound confusing, whether they should type it in the command box or the terminal.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jessica2828/ped#10

**Comment by Incogdino** [comment]
Maybe can add a glossary or some links to explain the more complicated terms

**Comment by SwaminathanViswa** [comment]
We could also add a sample example for the cd part. For example we could say,

"Assuming you have downloaded the jar file and transferred to your desktop, you can `cd Desktop` or equivalent in your operating system" 

and then they can carry on from there.
